name: Deploy Infrastructure

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

      # ... Add steps to configure and deploy Airflow or data pipeline

      - name: Save Terraform Outputs
        run: echo "::set-output name=redshift_endpoint::$(terraform output -raw redshift_cluster_endpoint)"
        id: terraform-outputs

      - name: Deploy Completed
        run: echo "Deployment completed!"

